import { BlockDefinition } from '../block-definition.types';

/**
 * `section` — l'unico contenitore del primo rilascio (ADR-21 § 5,
 * SPEC-F02-blocchi.md § 3.2). Nessuna prop dichiarata: qualunque prop
 * inviata produce `BLOCK_PROP_NOT_DECLARED`. Non contiene se stessa — la
 * profondità è 1 per costruzione nel primo rilascio.
 */
export const sectionBlock: BlockDefinition = {
  type: 'section',
  v: 1,
  props: {
    styleSpaceBefore: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'xs', 'sm', 'md', 'lg', 'xl'],
      default: { default: 'none' },
    },
    styleSpaceAfter: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'xs', 'sm', 'md', 'lg', 'xl'],
      default: { default: 'none' },
    },
    stylePadding: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'sm', 'md', 'lg'],
      default: { default: 'none' },
    },
    styleBackground: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'subtle', 'accent', 'inverse'],
      default: { default: 'none' },
    },
    columns: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['1', '2', '3', '4'],
      default: { default: '1' },
    },
    gap: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'sm', 'md', 'lg'],
      default: { default: 'none' },
    },
    alignItems: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['stretch', 'flex-start', 'center', 'flex-end'],
      default: { default: 'stretch' },
    },
    contentWidth: {
      kind: 'enum',
      required: false,
      values: ['boxed', 'full-width'],
      default: 'boxed',
    },
    maxWidth: {
      kind: 'enum',
      required: false,
      values: ['sm', 'md', 'lg', 'xl'],
      default: 'md',
    },
    columnRatio: {
      kind: 'enum',
      required: false,
      values: ['equal', '33-66', '66-33'],
      default: 'equal',
    },
    styleBackgroundColor: {
      kind: 'color',
      required: false,
    },
    stylePaddingTop: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    stylePaddingRight: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    stylePaddingBottom: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    stylePaddingLeft: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleMarginTop: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleMarginRight: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleMarginBottom: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleMarginLeft: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
  },
  children: { allow: ['heading', 'richText', 'image', 'button'] },
  migrations: [],
  enabled: true,
  meta: {
    label: 'Sezione',
    category: 'layout',
    icon: 'layout-board',
    props: {
      styleSpaceBefore: { label: 'Spazio prima', tab: 'style', order: 1 },
      styleSpaceAfter: { label: 'Spazio dopo', tab: 'style', order: 2 },
      stylePadding: { label: 'Spaziatura interna', tab: 'style', order: 3 },
      styleBackground: { label: 'Sfondo', tab: 'style', order: 4 },
      columns: {
        label: 'Colonne',
        tab: 'style',
        order: 5,
        help: 'Numero di colonne del contenitore',
      },
      gap: { label: 'Spaziatura tra colonne', tab: 'style', order: 6 },
      alignItems: { label: 'Allineamento verticale', tab: 'style', order: 7 },
      contentWidth: { label: 'Larghezza contenuto', tab: 'style', order: 8 },
      maxWidth: { label: 'Larghezza massima', tab: 'style', order: 9 },
      columnRatio: {
        label: 'Proporzione colonne',
        tab: 'style',
        order: 10,
        help: 'Significativa solo con 2 colonne',
      },
      styleBackgroundColor: { label: 'Colore di sfondo', tab: 'style', order: 11 },
      stylePaddingTop: { label: 'Padding superiore', tab: 'style', order: 12 },
      stylePaddingRight: { label: 'Padding destro', tab: 'style', order: 13 },
      stylePaddingBottom: { label: 'Padding inferiore', tab: 'style', order: 14 },
      stylePaddingLeft: { label: 'Padding sinistro', tab: 'style', order: 15 },
      styleMarginTop: { label: 'Margine superiore', tab: 'style', order: 16 },
      styleMarginRight: { label: 'Margine destro', tab: 'style', order: 17 },
      styleMarginBottom: { label: 'Margine inferiore', tab: 'style', order: 18 },
      styleMarginLeft: { label: 'Margine sinistro', tab: 'style', order: 19 },
    },
  },
};
