import { BlockDefinition } from '../block-definition.types';

/**
 * `section` — l'unico contenitore del primo rilascio (ADR-21 § 5,
 * SPEC-F02-blocchi.md § 3.2). Nessuna prop non dichiarata è ammessa: qualunque prop
 * non elencata qui produce `BLOCK_PROP_NOT_DECLARED`. Non contiene se stessa — la
 * profondità è 1 per costruzione nel primo rilascio.
 * `styleBackgroundType`/`styleBackgroundPosition`/`styleBackgroundSize`/
 * `styleGradientStart`/`styleGradientEnd` (ADR-50): tutte presentazione, non
 * validazione — restano dichiarate indipendentemente da quale sorgente di sfondo il
 * renderer sceglie di onorare, stesso principio di `maxWidth` sotto `contentWidth =
 * full-width` (ADR-33 § 1). Nessun bump di `v`, tutte opzionali con default.
 */
export const sectionBlock: BlockDefinition = {
  type: 'section',
  v: 1,
  props: {
    styleSpaceBefore: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'xs', 'sm', 'md', 'lg', 'xl'],
      default: { default: 'none' },
    },
    styleSpaceAfter: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'xs', 'sm', 'md', 'lg', 'xl'],
      default: { default: 'none' },
    },
    stylePadding: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'sm', 'md', 'lg'],
      default: { default: 'none' },
    },
    styleBackground: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'subtle', 'accent', 'inverse'],
      default: { default: 'none' },
    },
    columns: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['1', '2', '3', '4'],
      default: { default: '1' },
    },
    gap: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['none', 'sm', 'md', 'lg'],
      default: { default: 'none' },
    },
    alignItems: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['stretch', 'flex-start', 'center', 'flex-end'],
      default: { default: 'stretch' },
    },
    contentWidth: {
      kind: 'enum',
      required: false,
      values: ['boxed', 'full-width'],
      default: 'boxed',
    },
    maxWidth: {
      kind: 'enum',
      required: false,
      values: ['sm', 'md', 'lg', 'xl'],
      default: 'md',
    },
    columnRatio: {
      kind: 'enum',
      required: false,
      values: ['equal', '33-66', '66-33'],
      default: 'equal',
    },
    styleBackgroundColor: {
      kind: 'color',
      required: false,
    },
    styleColor: { kind: 'color', required: false },
    backgroundColor: { kind: 'color', required: false },
    color: { kind: 'color', required: false },
    stylePaddingTop: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    stylePaddingRight: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    stylePaddingBottom: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    stylePaddingLeft: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleMarginTop: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleMarginRight: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleMarginBottom: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleMarginLeft: {
      kind: 'enum',
      required: false,
      responsive: true,
      values: ['0', '4', '8', '12', '16', '24', '32', '48', '64', '96'],
      default: { default: '0' },
    },
    styleLayer: {
      kind: 'enum',
      required: false,
      values: ['base', 'raised', 'overlay', 'top'],
      default: 'base',
    },
    styleHideDesktop: {
      kind: 'boolean',
      required: false,
      default: false,
    },
    styleHideTablet: {
      kind: 'boolean',
      required: false,
      default: false,
    },
    styleHideMobile: {
      kind: 'boolean',
      required: false,
      default: false,
    },
    styleBorder: {
      kind: 'border',
      required: false,
    },
    styleShadow: {
      kind: 'shadow',
      required: false,
    },
    customCssClass: {
      kind: 'cssClassName',
      required: false,
    },
    customElementId: {
      kind: 'htmlId',
      required: false,
    },
    styleBackgroundImageRef: {
      kind: 'mediaRef',
      required: false,
    },
    styleOverlayColor: {
      kind: 'color',
      required: false,
    },
    styleOverlayOpacity: {
      kind: 'number',
      required: false,
      min: 0,
      max: 1,
    },
    // ADR-50: presentazione, non validazione — resta dichiarata e validata anche quando
    // `styleBackgroundType` seleziona un'altra sorgente di sfondo (stesso principio di
    // `maxWidth` sotto `contentWidth = full-width`, ADR-33 § 1).
    styleBackgroundType: {
      kind: 'enum',
      required: false,
      values: ['color', 'image', 'gradient'],
      default: 'color',
    },
    styleBackgroundPosition: {
      kind: 'enum',
      required: false,
      values: [
        'top left',
        'top center',
        'top right',
        'center left',
        'center center',
        'center right',
        'bottom left',
        'bottom center',
        'bottom right',
      ],
      default: 'center center',
    },
    styleBackgroundSize: {
      kind: 'enum',
      required: false,
      values: ['cover', 'contain', 'auto'],
      default: 'cover',
    },
    styleGradientStart: {
      kind: 'color',
      required: false,
    },
    styleGradientEnd: {
      kind: 'color',
      required: false,
    },
  },
  children: { allow: ['heading', 'richText', 'image', 'button', 'container', 'form'] },
  migrations: [],
  enabled: true,
  meta: {
    label: 'Sezione',
    category: 'layout',
    icon: 'layout-board',
    props: {
      styleSpaceBefore: { label: 'Spazio prima', tab: 'style', order: 1 },
      styleSpaceAfter: { label: 'Spazio dopo', tab: 'style', order: 2 },
      stylePadding: { label: 'Spaziatura interna', tab: 'style', order: 3 },
      styleBackground: { label: 'Sfondo', tab: 'style', order: 4 },
      columns: {
        label: 'Colonne',
        tab: 'style',
        order: 5,
        help: 'Numero di colonne del contenitore',
      },
      gap: { label: 'Spaziatura tra colonne', tab: 'style', order: 6 },
      alignItems: { label: 'Allineamento verticale', tab: 'style', order: 7 },
      contentWidth: { label: 'Larghezza contenuto', tab: 'style', order: 8 },
      maxWidth: { label: 'Larghezza massima', tab: 'style', order: 9 },
      columnRatio: {
        label: 'Proporzione colonne',
        tab: 'style',
        order: 10,
        help: 'Significativa solo con 2 colonne',
      },
      styleBackgroundColor: { label: 'Colore di sfondo', tab: 'style', order: 11 },
      styleColor: { label: 'Colore testo', tab: 'style', order: 12 },
      backgroundColor: { label: 'Colore di sfondo (fallback)', tab: 'style', order: 13 },
      color: { label: 'Colore testo (fallback)', tab: 'style', order: 14 },
      stylePaddingTop: { label: 'Padding superiore', tab: 'style', order: 12 },
      stylePaddingRight: { label: 'Padding destro', tab: 'style', order: 13 },
      stylePaddingBottom: { label: 'Padding inferiore', tab: 'style', order: 14 },
      stylePaddingLeft: { label: 'Padding sinistro', tab: 'style', order: 15 },
      styleMarginTop: { label: 'Margine superiore', tab: 'style', order: 16 },
      styleMarginRight: { label: 'Margine destro', tab: 'style', order: 17 },
      styleMarginBottom: { label: 'Margine inferiore', tab: 'style', order: 18 },
      styleMarginLeft: { label: 'Margine sinistro', tab: 'style', order: 19 },
      styleLayer: { label: 'Livello di sovrapposizione', tab: 'advanced', order: 20 },
      styleHideDesktop: { label: 'Nascondi su Desktop', tab: 'advanced', order: 21 },
      styleHideTablet: { label: 'Nascondi su Tablet', tab: 'advanced', order: 22 },
      styleHideMobile: { label: 'Nascondi su Mobile', tab: 'advanced', order: 23 },
      styleBorder: { label: 'Bordo', tab: 'style', order: 24 },
      styleShadow: { label: 'Ombra', tab: 'style', order: 25 },
      customCssClass: {
        label: 'Classe CSS personalizzata',
        tab: 'advanced',
        order: 26,
        help: 'Una o più classi separate da spazio: solo lettere, numeri, trattino, underscore.',
      },
      customElementId: {
        label: 'ID elemento personalizzato',
        tab: 'advanced',
        order: 27,
        help: 'Solo lettere, numeri, trattino, underscore — nessuno spazio.',
      },
      styleBackgroundImageRef: {
        label: 'Immagine di sfondo',
        tab: 'style',
        order: 28,
        help: 'Riferimento a un file della media library.',
      },
      styleOverlayColor: {
        label: 'Colore overlay',
        tab: 'style',
        order: 29,
        help: 'Colore esadecimale sovrapposto all\'immagine di sfondo.',
      },
      styleOverlayOpacity: {
        label: 'Opacità overlay',
        tab: 'style',
        order: 30,
        help: 'Valore da 0 (trasparente) a 1 (opaco).',
      },
      styleBackgroundType: {
        label: 'Tipo sfondo',
        tab: 'style',
        order: 31,
        help: 'Colore, immagine o gradiente.',
      },
      styleBackgroundPosition: {
        label: 'Posizione sfondo',
        tab: 'style',
        order: 32,
        help: 'Applicata solo quando il tipo sfondo è Immagine.',
      },
      styleBackgroundSize: {
        label: 'Dimensione sfondo',
        tab: 'style',
        order: 33,
        help: 'Applicata solo quando il tipo sfondo è Immagine.',
      },
      styleGradientStart: {
        label: 'Colore iniziale gradiente',
        tab: 'style',
        order: 34,
        help: 'Applicato solo quando il tipo sfondo è Gradiente.',
      },
      styleGradientEnd: {
        label: 'Colore finale gradiente',
        tab: 'style',
        order: 35,
        help: 'Applicato solo quando il tipo sfondo è Gradiente.',
      },
    },
  },
};
